export default function Home() {
  return (
    <>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
      <h1>JE SUIS UNE PIZZA QUI VEUT RENTRER DANS TON ESTOMAC !!!</h1>
    </>
  );
}
